#!/bin/python

from pick import pick

title = 'Please pick the best category which defines this server'
options = ["web", "db", "kvm"]
option, index = pick(options, title)
filepath = "/home/brian/ansible/test"
name = "test"

with open(filepath, "r") as in_file:
        buf = in_file.readlines()

with open(filepath, "w") as out_file:
        for line in buf:
                if line == "[" + option + "]\n":
                        line = line + name + "\n"
                        print "Success! A line has been written to " + filepath
                out_file.write(line)
